# Generated by Django 5.2.5 on 2025-08-28 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='nombre',
            new_name='modelo',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='Categoria',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='especificaciones',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='stock',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='direccion',
        ),
        migrations.AddField(
            model_name='producto',
            name='almacenamiento',
            field=models.FloatField(default=512),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='color',
            field=models.CharField(default='gris', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='detalles',
            field=models.TextField(default='con mouse', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='marca',
            field=models.CharField(default='MacBook', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='procesador',
            field=models.CharField(default='M1 Pro', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='ram',
            field=models.FloatField(default=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='serial',
            field=models.CharField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='edad',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.FloatField(),
        ),
    ]
