# Generated by Django 5.2.5 on 2025-08-28 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_producto_almacenamiento_alter_producto_color_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='telefono',
        ),
        migrations.AddField(
            model_name='usuario',
            name='cargo',
            field=models.CharField(default=22, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='usuarios/'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='edad',
            field=models.PositiveIntegerField(default=18),
            preserve_default=False,
        ),
    ]
