# Generated by Django 5.2.5 on 2025-08-29 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_venta'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudRegistro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=150)),
                ('tipo_identificacion', models.CharField(max_length=5)),
                ('numero_identificacion', models.CharField(max_length=30)),
                ('edad', models.IntegerField()),
                ('direccion', models.CharField(max_length=255)),
                ('correo', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=20)),
                ('cargo', models.CharField(max_length=50)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
