# Generated by Django 5.2.5 on 2025-08-29 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_solicitudregistro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudregistro',
            name='cargo',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='solicitudregistro',
            name='numero_identificacion',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='solicitudregistro',
            name='tipo_identificacion',
            field=models.CharField(max_length=20),
        ),
    ]
