# Generated by Django 5.2.5 on 2025-09-01 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_usuario_direccion_usuario_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='edad',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
