# Generated by Django 5.2.5 on 2025-09-01 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_solicitudcompra'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solicitudcompra',
            old_name='Producto',
            new_name='producto',
        ),
    ]
