# Generated by Django 5.2.5 on 2025-09-01 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_rename_producto_solicitudcompra_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='foto_perfil',
            field=models.ImageField(blank=True, default='usuarios/perfil.png', null=True, upload_to='fotos_perfil/'),
        ),
    ]
