# Generated by Django 5.2.5 on 2025-09-05 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_usuario_foto_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudcompra',
            name='metodo_pago',
            field=models.CharField(choices=[('tarjeta_credito', 'Tarjeta de Crédito'), ('tarjeta_debito', 'Tarjeta de Débito'), ('transferencia', 'Transferencia Bancaria'), ('efectivo', 'Efectivo')], default='tarjeta_credito', max_length=50),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='cargo',
            field=models.CharField(choices=[('cliente', 'Cliente'), ('admin', 'Administrador')], default='cliente', max_length=20),
        ),
    ]
