# Generated by Django 5.2.5 on 2025-09-05 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_solicitudcompra_metodo_pago_alter_usuario_cargo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Categoria',
        ),
    ]
