# Generated by Django 5.2.5 on 2025-09-05 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_delete_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudregistro',
            name='tipo_identificacion',
            field=models.CharField(choices=[('CC', 'Cédula de ciudadanía'), ('TI', 'Tarjeta de identidad'), ('CE', 'Cédula de extranjería')], default='CC', max_length=2),
        ),
    ]
